In [2]:
import numpy as np


def answer(ans):
    print('Answer:\n', ans)

# 第１章 
## 問１

In [3]:
a = np.array([[9, 8, 7 ,6],
             [5, 4, 3, 2],
             [1, 0, -1, -2]])

### 第3行

In [4]:
answer(a[2])

Answer:
 [ 1  0 -1 -2]


### 第4列

In [5]:
answer(a[:, 3])

Answer:
 [ 6  2 -2]


### (1, 3)成分

In [6]:
answer(a[0, 2])

Answer:
 7


### (2, 4)成分

In [7]:
answer(a[1, 3])

Answer:
 2


### (3, 2)成分

In [8]:
answer(a[2, 1])

Answer:
 0


## 問２

### (i, j)成分がiとjの最大公約数になるような4次正方行列

In [9]:
gcf_matrix = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        gcf_matrix[i, j] = np.gcd(i+1, j+1)

answer(gcf_matrix)

Answer:
 [[1. 1. 1. 1.]
 [1. 2. 1. 2.]
 [1. 1. 3. 1.]
 [1. 2. 1. 4.]]


### (i, j)成分がiとjの最小公倍数であるような4次正方行列

In [10]:
lem_matrix = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        lem_matrix[i, j] = np.lcm(i+1, j+1)

answer(lem_matrix)

Answer:
 [[ 1.  2.  3.  4.]
 [ 2.  2.  6.  4.]
 [ 3.  6.  3. 12.]
 [ 4.  4. 12.  4.]]


## 問３

In [11]:
a = np.array([[0, 1, 2],
              [3, 1, -1]])

b = np.array([[3, -2, 1],
              [1, 0, -1]])

### (1)

In [12]:
answer(a - 2 * b)

Answer:
 [[-6  5  0]
 [ 1  1  1]]


### (2)

In [13]:
answer(3 * a + 4 * b)

Answer:
 [[12 -5 10]
 [13  3 -7]]


### (3)

In [14]:
answer(-1 * a + b)

Answer:
 [[ 3 -3 -1]
 [-2 -1  0]]


## 問４

In [15]:
a = np.array([[-1, 0, 3], 
              [2, 1, 1]])

b = np.array([[3, -2], 
              [7, 1]])

### AB

In [16]:
try:
    np.dot(a, b)
except:
    answer('計算不能')

Answer:
 計算不能


### BA

In [17]:
answer(np.dot(b, a))

Answer:
 [[-7 -2  7]
 [-5  1 22]]


## 問５❌

## 問６ 省略

## 問７

### (1)❌

### (2)

In [18]:
a = np.array([[1, 1],
              [1, 1]])

b = np.array([[2, 2], 
              [-2, -2]])

answer(np.dot(a, b))

Answer:
 [[0 0]
 [0 0]]


### (3) 省略

## 問８

In [30]:
a = np.array([[0, 1, 1, 1], 
              [0, 0, 1, 1], 
              [0, 0, 0, 1],
              [0, 0, 0, 0]])

b = np.array([[2, -3, 1],
              [1, -2, 1],
              [1, -3, 2]])


for mat in [a, b]:

    already_answered = False
    if np.all(np.dot(mat, mat) == mat):
        answer(f'{mat}\nは、べき等行列')
        already_answered = True

    #-------------------------------------------------------

    pre_mat = mat

    for time in range(1, 101):
        if np.all(np.dot(pre_mat, mat) == np.zeros((mat.shape[0], mat.shape[1]))):
            answer(f'{mat}\nは、べき零行列')

            already_answered = True
            break

        pre_mat = np.dot(pre_mat, mat)

    if not already_answered:
        answer(f'{mat}\nは、べき零行列でもべき等行列でもない')

Answer:
 [[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]
は、べき零行列
Answer:
 [[ 2 -3  1]
 [ 1 -2  1]
 [ 1 -3  2]]
は、べき等行列


## 問９

### A

In [31]:
a = np.array([[1], 
              [2],
              [3]])

answer(a.T)

Answer:
 [[1 2 3]]


### b

In [32]:

b = np.array([[4, 3],
              [2, 1]])

answer(b.T)

Answer:
 [[4 2]
 [3 1]]


## 問10~16❌

## 基礎問題

### 1.1~1.2❌

### 1.3

In [25]:
la = np.array([[1, 2, -1],
              [3, 1, 0]])

lb = np.array([[2, 0, 1], 
               [-1, 1, 0], 
               [0 ,1, 3]])

a = np.array([[1],
              [-2],
              [1]])

b = np.array([[3, 2]])

#### (1)

In [26]:
answer(np.dot(la.T, la))

Answer:
 [[10  5 -1]
 [ 5  5 -2]
 [-1 -2  1]]


#### (2)

In [27]:
answer(np.dot(la, la.T))

Answer:
 [[ 6  5]
 [ 5 10]]


#### (3)

In [28]:
answer(np.dot(lb, lb))

Answer:
 [[ 4  1  5]
 [-3  1 -1]
 [-1  4  9]]


#### (4)

In [29]:
answer(np.dot(la, lb))

Answer:
 [[ 0  1 -2]
 [ 5  1  3]]


#### (5)

In [30]:
answer(np.dot(a.T, np.dot(lb, a)))

Answer:
 [[10]]


#### (6)

In [32]:
answer(np.dot(a, b))

Answer:
 [[ 3  2]
 [-6 -4]
 [ 3  2]]


### 1.4

In [34]:
x = np.array([[0, 1],
              [1, 0]])

y = np.array([[0, -1j],
              [1j, 0]])

z = np.array([[1, 0],
              [0, -1]])

#### (1)

In [35]:
answer(np.dot(x, x))

Answer:
 [[1 0]
 [0 1]]


In [36]:
answer(np.dot(y, y))

Answer:
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [37]:
answer(np.dot(z, z))

Answer:
 [[1 0]
 [0 1]]


#### (2)

In [38]:
answer(np.dot(x, y) + np.dot(y, x))

Answer:
 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [40]:
answer(np.dot(y, z) + np.dot(z, y))

Answer:
 [[ 0.+0.j  0.+0.j]
 [ 0.+0.j -0.+0.j]]


In [41]:
answer(np.dot(z, x) + np.dot(x, z))

Answer:
 [[0 0]
 [0 0]]


#### (3)

In [43]:
equal_matrix = np.dot(x, y) - np.dot(y, x) == 2j * z

answer("成り立つ" if np.all(equal_matrix) else "成り立たない")

Answer:
 成り立つ


In [44]:
equal_matrix = np.dot(y, z) - np.dot(z, y) == 2j * x

answer("成り立つ" if np.all(equal_matrix) else "成り立たない")

Answer:
 成り立つ


In [46]:
equal_matrix = np.dot(z, x) - np.dot(x, z) == 2j * y

answer("成り立つ" if np.all(equal_matrix) else "成り立たない")

Answer:
 成り立つ
